spring:
  application:
    name: course-catalog-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: test
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
message: Application started in default profile

#---
#spring:
#config:
#    activate:
#      on-profile: prod
#message: Hello from prod profile
#
#---
#spring:
#  config:
#    activate:
#      on-profile: qa
#message: Hello from qa profile
